Nome: [Anna Beatriz Oki] | UDF | Sistemas de Informação | Ciência de Dados

## Manipulação de Dados Tabulares com Pandas - Funções Básicas

- Tipos de Dados com Pandas
- Renomeando Colunas
- Selecionando Linhas e Colunas
- Adicionando e Removendo Colunas
- Operações Básicas - Consultas
- Operações Básicas - Ordenação
- Operações Básicas - Combinando DataFrames
- Operações Básicas - Salvando DataFrames

In [24]:
import pandas as pd

In [25]:
cidades = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São Paulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 1223237, 1710.00]
    ], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'])

cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [26]:
# df = pd.read_csv('qualidade_vinho.csv', sep=',', header=0) # df.head(2) # Não executado: arquivo qualidade_vinho.csv não disponível

In [27]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [28]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

      Estado    Cidade  Habitantes  Salário-Médio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

In [29]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [30]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do dataframe

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      str
 1   Cidade         5 non-null      str
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 292.0 bytes

In [31]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'], dtype='str')

In [32]:
cidades['Salário-Médio'].describe() # Retorna um objeto DataFrame com as medidas estatísticas para cada coluna

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-Médio, dtype: float64

## Tipos de Dados com Pandas

In [33]:
cidades.dtypes
cidades.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      str
 1   Cidade         5 non-null      str
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 292.0 bytes

In [34]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')
cidades.dtypes

Estado               str
Cidade               str
Habitantes       float64
Salário-Médio    float64
dtype: object

In [35]:
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021', '3-12-2021']
cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y') # Dia, Mês, Ano

cidades

           Estado         Cidade  Habitantes  Salário-Médio       Data
0          Paraná       Londrina    575377.0         1356.0 2021-08-03
1       São Paulo     São Carlos    254484.0         1508.0 2021-09-03
2  Santa Catarina  Florianópolis    508826.0         1798.0 2021-10-03
3          Paraná       Curitiba   1963726.0         2293.0 2021-11-03
4       São Paulo       Campinas   1223237.0         1710.0 2021-12-03

cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano
cidades # Novo Formato

## Renomeando Colunas

In [36]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data - Censo'}, inplace=True)
cidades

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina      575377.0         1356.0   2021-08-03
1       São Paulo     São Carlos      254484.0         1508.0   2021-09-03
2  Santa Catarina  Florianópolis      508826.0         1798.0   2021-10-03
3          Paraná       Curitiba     1963726.0         2293.0   2021-11-03
4       São Paulo       Campinas     1223237.0         1710.0   2021-12-03

## Selecionando Linhas e Colunas

In [37]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']] # Seleciona as duas colunas com os nomes especificados
cidadesHab

   N Habitantes  Salário-Médio
0      575377.0         1356.0
1      254484.0         1508.0
2      508826.0         1798.0
3     1963726.0         2293.0
4     1223237.0         1710.0

In [38]:
cidades.loc[[1, 2]] # Seleciona as duas linhas com os nomes especificados (note que o "rótulo" de cada linha está...)

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   2021-09-03
2  Santa Catarina  Florianópolis      508826.0         1798.0   2021-10-03

In [39]:
cidades.iloc[1:3] # Seleciona as linhas do dataframe original, referentes ao índice determinado

           Estado         Cidade  N Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos      254484.0         1508.0   2021-09-03
2  Santa Catarina  Florianópolis      508826.0         1798.0   2021-10-03

In [40]:
cidades.iloc[:, 0:2] # Seleciona todas as linhas e as duas primeiras colunas do dataframe original

           Estado         Cidade
0          Paraná       Londrina
1       São Paulo     São Carlos
2  Santa Catarina  Florianópolis
3          Paraná       Curitiba
4       São Paulo       Campinas

In [41]:
cidades.iloc[1:3, :3] # Seleciona as duas primeiras linhas e as três primeiras colunas

           Estado         Cidade  N Habitantes
1       São Paulo     São Carlos      254484.0
2  Santa Catarina  Florianópolis      508826.0

In [42]:
cidades.iloc[:, [1, 3, 0, 2]] # Seleciona todas as linhas e as colunas determinadas

          Cidade  Salário-Médio          Estado  N Habitantes
0       Londrina         1356.0          Paraná      575377.0
1     São Carlos         1508.0       São Paulo      254484.0
2  Florianópolis         1798.0  Santa Catarina      508826.0
3       Curitiba         2293.0          Paraná     1963726.0
4       Campinas         1710.0       São Paulo     1223237.0

## Adicionando e Removendo Colunas

In [43]:
cidades.insert(2, 'Sigla', ['PR', 'SP', 'SC', 'PR', 'SP']) # Adiciona novos dados no índice dois
cidades.insert(2, 'Sigla-Repetida', cidades['Sigla']) # Adiciona uma coluna repetida "Sigla"
cidades

,Estado,Cidade,Sigla-Repetida,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,PR,575377.0,1356.0,2021-08-03
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,2021-09-03
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,2021-10-03
3,Paraná,Curitiba,PR,PR,1963726.0,2293.0,2021-11-03
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,2021-12-03

In [44]:
cidades.pop('Sigla-Repetida')
# ou
# cidades = cidades.drop(['Sigla-Repetida'], axis=1)
cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03
1,São Paulo,São Carlos,SP,254484.0,1508.0,2021-09-03
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03
4,São Paulo,Campinas,SP,1223237.0,1710.0,2021-12-03

## Operações Básicas - Consultas

In [45]:
cidades.query('`Salário-Médio` > 1400.0')

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
1,São Paulo,São Carlos,SP,254484.0,1508.0,2021-09-03
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03
4,São Paulo,Campinas,SP,1223237.0,1710.0,2021-12-03

In [46]:
cidades.query('Estado == "São Paulo"')

      Estado      Cidade Sigla  N Habitantes  Salário-Médio Data - Censo
1  São Paulo  São Carlos    SP      254484.0         1508.0   2021-09-03
4  São Paulo    Campinas    SP     1223237.0         1710.0   2021-12-03

In [47]:
cidades.query('`N Habitantes` > 500000 and `N Habitantes` < 1300000')

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03
4,São Paulo,Campinas,SP,1223237.0,1710.0,2021-12-03

## Operações Básicas - Ordenação

In [48]:
cidades.sort_values(by='Cidade', inplace=True)
cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
4,São Paulo,Campinas,SP,1223237.0,1710.0,2021-12-03
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03
1,São Paulo,São Carlos,SP,254484.0,1508.0,2021-09-03

In [49]:
cidades.sort_values(by='Salário-Médio', inplace=True)
cidades

,Estado,Cidade,Sigla,N Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,2021-08-03
1,São Paulo,São Carlos,SP,254484.0,1508.0,2021-09-03
4,São Paulo,Campinas,SP,1223237.0,1710.0,2021-12-03
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,2021-10-03
3,Paraná,Curitiba,PR,1963726.0,2293.0,2021-11-03

## Operações Básicas - Combinando DataFrames

In [50]:
cidades_salarios = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 1356.00],
        ['São Paulo', 'São Carlos', 1508.00],
        ['Santa Catarina', 'Florianópolis', 1798.00],
        ['Paraná', 'Curitiba', 2293.00],
        ['São Paulo', 'Campinas', 1710.00]
    ], columns=['Estado', 'Cidade', 'Salário-Médio'])

cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [51]:
cidades_pop = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826],
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ], columns=['Cidade', 'Habitantes'])

cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [52]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade")

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

In [53]:
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade", how="outer")

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

In [54]:
cidades_df1 = pd.DataFrame(
    [
        ['Londrina', 575377],
        ['São Carlos', 254484],
        ['Florianópolis', 508826],
    ], columns=['Cidade', 'Habitantes'])

cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [55]:
cidades_df2 = pd.DataFrame(
    [
        ['Curitiba', 1963726],
        ['Campinas', 1223237]
    ], columns=['Cidade', 'Habitantes'])

cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [56]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

## Operações Básicas - Salvando DataFrames

In [57]:
cidades.to_csv("my_df.csv")
cidades.to_html("my_df.html")
cidades.to_json("my_df.json")

C:\Users\anna.correa\AppData\Local\Temp\ipykernel_11316\1427583.py:3: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  cidades.to_json("my_df.json")